
---
dependencies:

  # advanced_share: ^0.1.0
  cached_network_image: ^1.1.2
  camera: ^0.5.8+2
  carousel_pro: ^1.0.0
  carousel_slider: ^1.0.0
  cloud_firestore: ^0.13.7
  cupertino_icons: ^0.1.3
  image_picker: ^0.6.7+4
  # custom_multi_image_picker: ^2.1.24
  # device_id: any
  device_info: ^0.4.2+7
  firebase_auth: ^0.16.1
  firebase_database: ^3.1.6
  firebase_messaging: ^6.0.16
  firebase_storage: ^3.1.6
  flutter:
    sdk: flutter
  flutter_facebook_login: ^2.0.1
  flutter_webview_plugin: ^0.3.10+1
  font_awesome_flutter: ~
  http: any
  image_cropper: ^1.3.1
  intl: ^0.16.0
  path_provider: ^1.6.11
  permission: ^0.1.7
  progress_hud: ^1.1.0
  queries: ^0.1.14
  random_string: ^2.1.0
  rxdart: ^0.24.1
  share: ^0.6.5
  animated_text_kit: ^2.2.0
  xml: ^4.1.0
  package_info: ^0.4.3
  timeline_list: ^0.0.5
  # speech_bubble: ^0.0.4
  rflutter_alert: ^1.0.2
  shared_preferences: ^0.5.10
  flare_flutter: ^2.0.6
  xml2json: ^4.3.0
  progress_dialog: ^1.2.4
  multi_image_picker: ^4.7.14
  flutter_absolute_path: ^1.0.6
  connectivity: ^0.4.9+2
  file_picker: ^2.0.0
  webview_flutter: ^1.0.7
  
description: "A new Flutter application."
dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
flutter:

  assets:

    - images/ic_shutter_1.png
    - images/place_h.png
    - images/placeholder_face.png
    - images/map.png
    - images/pay.png
    - images/polybag.png
    - images/box.png
    - assets/image_pro.gif
    - assets/image_pro1.gif
    - assets/Status E_S.flr
    - assets/animation.flr
    - images/name.png
    - images/sp_bla.jpg
    - images/sp_bla2.jpg
    - images/sp_bla4.jpg
    - images/sp_bla5.jpg
    - images/tonlogo.png
    - images/sp_1.jpg
    - images/sp_2.jpg
    - images/sp_3.jpg
    - images/sp_4.jpg
    - images/sp.jpg
    - images/sp_new.jpg
    - images/sp_new1.jpg
    - images/sp_main.jpg
    
  uses-material-design: true
  fonts:

    - family: ggg
      fonts:
        - asset: assets/fonts/OLRoundGothicLight.ttf

    - family: RobotoSlab_Thin
      fonts:
        - asset: assets/fonts/RobotoSlab-Thin.ttf

    - family: RobotoSlab_Bold
      fonts:
        - asset: assets/fonts/RobotoSlab-Bold.ttf

    - family: RobotoSlab_Light
      fonts:
        - asset: assets/fonts/RobotoSlab-Light.ttf

    - family: RobotoSlab_Regular
      fonts:
        - asset: assets/fonts/RobotoSlab-Regular.ttf



name: threadon
version: 1.0.0+1
